# Global Project Settings
project_name: "phoenix"
default_region: "us-east-2"

# Infrastructure State Management (for backend.hcl)
backend:
  bucket: "gabriel-tf-state-2026"
  profile: "mgmt"

# Organization Accounts
accounts:
  mgmt: "086739225244"
  dev:  "195481994910"
  prod: "212984412001"

# Account Emails
dev_email: "gabriel.jsh+dev2@gmail.com"
prod_email: "gabriel.jsh+prod2@gmail.com"

# Organization user
sso_admin_user: "Gabe"
