# Global Project Settings
platform_name: "phoenix"
default_region: "us-east-2"

# Infrastructure State Management (for backend.hcl)
backend:
  bucket: "gabriel-tf-state-2026"
  profile: "mgmt"

# Organization Accounts
accounts:
  mgmt: "086739225244"
  dev:  "195481994910"
  prod: "212984412001"

# Account Emails
dev_email: "gabriel.jsh+dev2@gmail.com"
prod_email: "gabriel.jsh+prod2@gmail.com"

# Organization user
sso_admin_user: "Gabe"

# Service: VST Shop
vst_shop:
  frontend:
    user_pool_id: "us-east-2_V9hhjw2Y5"
    client_id: "2p1utd8g6jkts9qp59n7b5k9le"
    api_url: "https://g6jnm33pu7.execute-api.us-east-2.amazonaws.com/dev"
