# üåê Phoenix Platform Configuration

# Global Project Settings
platform_name: "phoenix"
default_region: "us-east-2"

# Infrastructure State Management
# The bucket where your remote terraform.tfstate files will be stored.
backend:
  bucket: "your-unique-state-bucket-name"
  profile: "mgmt"

# Organization Accounts
# Replace with your 12-digit AWS Account IDs
accounts:
  mgmt: "123456789012"
  dev:  "123456789012"
  prod: "123456789012"

# Account Identity
# Used for AWS Organization account creation and notifications
dev_email: "your.email+dev@example.com"
prod_email: "your.email+prod@example.com"
sso_admin_user: "AdminUser"
