name: "VSTShop Deploy Prod"

on:
  pull_request:
    branches: [ "master" ]
    paths:
      - 'infra/workloads/prod/**'
      - 'services/vstshop-frontend/**'
      - 'infra/modules/**'
      - '.github/workflows/vstshop-deploy-prod.yml'

  push:
    branches: [ "master" ]
    paths:
      - 'infra/workloads/prod/**'
      - 'services/vstshop-frontend/**'
      - 'infra/modules/**'
      - '.github/workflows/vstshop-deploy-prod.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  TF_DIR: "infra/workloads/prod/vstshop"
  SITE_DIR: "services/vstshop-frontend"
  TF_VAR_stripe_secret_key: ${{ secrets.STRIPE_SECRET_KEY }}
  TF_VAR_stripe_webhook_secret: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
  AWS_REGION: "us-east-2"

jobs:
  setup:
  # --- JOB 1: SCRAPE ---
    name: "Scrape Config"
    runs-on: ubuntu-latest
    outputs:
      mgmt_account: ${{ steps.vars.outputs.mgmt_account }}
      prod_account: ${{ steps.vars.outputs.prod_account }}
    steps:
      - uses: actions/checkout@v4
      - name: Extract Variables
        id: vars
        run: |
          echo "mgmt_account=$(yq '.accounts.mgmt' config.yaml)" >> $GITHUB_OUTPUT
          echo "prod_account=$(yq '.accounts.prod' config.yaml)" >> $GITHUB_OUTPUT

 # --- JOB 2: BUILD LAYERS ---
  build-layers:
    name: "Build Lambda Layers"
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          mkdir -p infra/modules/vstshop/backend/layer/python
          pip install -r infra/modules/vstshop/backend/requirements.txt -t infra/modules/vstshop/backend/layer/python/
      - name: Upload Layer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-layer
          path: infra/modules/vstshop/backend/layer/python/

  plan:
  # --- JOB 3: BUILD LAYERS ---
    name: "Production Plan"
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: true

      - name: Download Layer Artifact
        uses: actions/download-artifact@v4
        with:
          name: lambda-layer
          path: infra/modules/vstshop/backend/layer/python/

      - name: Auth Prod
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ needs.setup.outputs.mgmt_account }}:role/github-actions-oidc-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Role Chain to Prod
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-chaining: true
          role-to-assume: arn:aws:iam::${{ needs.setup.outputs.prod_account }}:role/terraform-execution-role-prod

      - name: Terraform Init & Plan
        id: plan
        working-directory: ${{ env.TF_DIR }}
        run: |
          terraform init -backend-config=../../../backend.ci.hcl
          terraform plan -no-color -input=false

      - name: Update Pull Request
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Prod Environment Plan ðŸ“–
            <details><summary>Show Plan</summary>
            \`\`\`${process.env.PLAN}\`\`\`
            </details>`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

  apply:
  # --- JOB 4: APPLY---
    name: "Production Apply"
    needs: [setup, plan]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    environment: production # This triggers the Manual Approval gate in GitHub!
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: true

      - name: Download Layer Artifact
        uses: actions/download-artifact@v4
        with:
          name: lambda-layer
          path: infra/modules/vstshop/backend/layer/python/


      - name: Auth Prod
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ needs.setup.outputs.mgmt_account }}:role/github-actions-oidc-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Role Chain to Prod
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-chaining: true
          role-to-assume: arn:aws:iam::${{ needs.setup.outputs.prod_account }}:role/terraform-execution-role-prod

      - name: Terraform Init & Apply
        working-directory: ${{ env.TF_DIR }}
        run: |
          terraform init -backend-config=../../../backend.ci.hcl
          terraform apply -auto-approve -input=false

      - name: Build Frontend
        run: |
          cd ${{ env.SITE_DIR }}
          npm install
          # This confirms Terraform successfully wrote the .env file here
          ls -la .env
          npm run build

      - name: Get Infra Outputs
        id: infra
        working-directory: ${{ env.TF_DIR }}
        run: |
          echo "BUCKET_NAME=$(terraform output -raw s3_bucket_name)" >> $GITHUB_OUTPUT
          echo "DIST_ID=$(terraform output -raw distribution_id)" >> $GITHUB_OUTPUT

      - name: Deploy Frontend to S3
        run: |
          # Sync the compiled 'dist' folder
          aws s3 sync "${{ env.SITE_DIR }}/dist" s3://${{ steps.infra.outputs.BUCKET_NAME }} --delete
          aws cloudfront create-invalidation --distribution-id ${{ steps.infra.outputs.DIST_ID }} --paths "/*"
